### ISSUE TITLE
Manifests are removed when any lockfile exists

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#1245]
## Overview

Lockfile and manifest detection in `phylum status` and `phylum init` commands are excluding valid manifest files. These commands return/show _only_ lockfiles when _any_ lockfile is found at or above the directory of a detected manifest file.

## How To Reproduce

Steps to reproduce this behavior:

1. Clone the [`astral-sh/ruff` repo](https://github.com/astral-sh/ruff) as an example containing lockfiles and manifests for multiple different ecosystems: `git clone git@github.com:astral-sh/ruff.git`
2. Run `phylum status` from the root of the `ruff` repo
3. See a total of only six (6) lockfiles reported:
   ```
   ❯ phylum status
   Project: null
   Group: null
   Project Root: null
   Lockfiles:
    - path: ./playground/package-lock.json
      type: npm
    - path: ./playground/api/package-lock.json
      type: npm
    - path: ./Cargo.lock
      type: cargo
    - path: ./docs/requirements.txt
      type: pip
    - path: ./docs/requirements-insiders.txt
      type: pip
    - path: ./scripts/benchmarks/poetry.lock
      type: poetry
   ```
4. See that some expected manifests are not included in the results:
   ```
   ./pyproject.toml
   ./scripts/pyproject.toml
   ./crates/flake8_to_ruff/pyproject.toml
   ```

## Expected Behavior

Repositories with a mix of ecosystems (e.g., monorepos) should report all the lockfiles and manifests, only filtering out manifests *for the same lockfile type* when there is a lockfile at or above the level of the manifest. In other words, this should work like workspace detection does, but isolated for each ecosystem/lockfile type.

## Additional Context

This issue can serve as the record for discussing the possibilities and any justification if the behavior described here is not considered a bug.

The code in question is believed to be in the `find_lockable_files_at` function in `lockfile/src/lib.rs`: https://github.com/phylum-dev/cli/blob/main/lockfile/src/lib.rs#L314-L316

With these lines commented out, the result of `phylum status` changes to include a lot more files:

<details><summary>All lockfiles and manifests in ruff repo (click to expand)</summary>
<p>

```
❯ /Users/maxrake/dev/phylum/localdev/cli/target/debug/phylum status
Project: null
Group: null
Project Root: null
Lockfiles:
 - path: ./playground/package-lock.json
   type: npm
 - path: ./playground/api/package-lock.json
   type: npm
 - path: ./Cargo.lock
   type: cargo
 - path: ./docs/requirements.txt
   type: pip
 - path: ./docs/requirements-insiders.txt
   type: pip
 - path: ./scripts/benchmarks/poetry.lock
   type: poetry
 - path: ./Cargo.toml
   type: cargo
 - path: ./crates/ruff_python_literal/Cargo.toml
   type: cargo
 - path: ./crates/ruff_python_trivia/Cargo.toml
   type: cargo
 - path: ./crates/ruff_index/Cargo.toml
   type: cargo
 - path: ./crates/ruff_workspace/Cargo.toml
   type: cargo
 - path: ./crates/ruff_python_parser/Cargo.toml
   type: cargo
 - path: ./crates/ruff_python_formatter/Cargo.toml
   type: cargo
 - path: ./crates/ruff_macros/Cargo.toml
   type: cargo
 - path: ./crates/ruff_python_codegen/Cargo.toml
   type: cargo
 - path: ./crates/ruff_dev/Cargo.toml
   type: cargo
 - path: ./crates/ruff_benchmark/Cargo.toml
   type: cargo
 - path: ./crates/ruff_linter/Cargo.toml
   type: cargo
 - path: ./crates/ruff_shrinking/Cargo.toml
   type: cargo
 - path: ./crates/ruff_source_file/Cargo.toml
   type: cargo
 - path: ./crates/ruff_cli/Cargo.toml
   type: cargo
 - path: ./crates/ruff_text_size/Cargo.toml
   type: cargo
 - path: ./crates/ruff_python_index/Cargo.toml
   type: cargo
 - path: ./crates/ruff_wasm/Cargo.toml
   type: cargo
 - path: ./crates/ruff_cache/Cargo.toml
   type: cargo
 - path: ./crates/ruff_python_semantic/Cargo.toml
   type: cargo
 - path: ./crates/ruff_notebook/Cargo.toml
   type: cargo
 - path: ./crates/ruff_python_ast/Cargo.toml
   type: cargo
 - path: ./crates/ruff_formatter/Cargo.toml
   type: cargo
 - path: ./crates/ruff_diagnostics/Cargo.toml
   type: cargo
 - path: ./crates/ruff_python_resolver/Cargo.toml
   type: cargo
 - path: ./crates/ruff_python_stdlib/Cargo.toml
   type: cargo
 - path: ./crates/flake8_to_ruff/Cargo.toml
   type: cargo
 - path: ./crates/flake8_to_ruff/pyproject.toml
   type: pip
 - path: ./crates/flake8_to_ruff/examples/cryptography/pyproject.toml
   type: pip
 - path: ./playground/package.json
   type: npm
 - path: ./playground/api/package.json
   type: npm
 - path: ./pyproject.toml
   type: pip
 - path: ./scripts/pyproject.toml
   type: pip
 - path: ./scripts/benchmarks/pyproject.toml
   type: pip
 - path: ./fuzz/Cargo.toml
   type: cargo
```

</p>
</details>

There is one argument that most of these files _should_ be filtered out since they are manifest files for a Cargo workspace. There is another argument that providing _all_ options (even if there are many) is desirable for situations like an interactive use of `phylum init`, where the user selects from the complete list of _possibilities_ (i.e., they perform the filtering instead of `phylum`).
