### ISSUE TITLE
Consider use of `rust-cache` for CI

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/cli#337]
After reading [this blog post](https://www.reillywood.com/blog/rust-faster-ci/) about results in [nushell](https://github.com/nushell/nushell), I believe we could benefit from using `rust-cache` in our CI builds.

**Comment by cd-work** [comment]
One thing I'd like to mention is that with Rust caching in CI one has to be careful not to cache too much. I've seen in multiple of my own repos that caching can sometimes initially boost build times but over the long term slow them down when the caches build up to become unwieldy.

**Comment by kylewillmon** [comment]
> One thing I'd like to mention is that with Rust caching in CI one has to be careful not to cache too much. I've seen in multiple of my own repos that caching can sometimes initially boost build times but over the long term slow them down when the caches build up to become unwieldy.

It looks like `nushell` is using a version number in their [cache key](https://github.com/nushell/nushell/blob/ac48f5a318adc7204700dd10cc8092d5d864659d/.github/workflows/ci.yml#L44) to avoid this. If/when the build slows down, they can simply bump that version and bust the cache.

We could do something like that. Or we could even automatically bump the key once a month or so by using something like this:

```
  - name: Set cache version
    run: echo 'cache_version=v'$(date '+%Y.%m') >> $GITHUB_ENV
  - uses: Swatinem/rust-cache@v1
    with:
      key: ${{ env.cache_version }}
```
