### ISSUE TITLE
Update `phylum_project` format

### ISSUE THREAD

**Issue by louislang** [phylum-dev/cli#904]
# Overview
We've recently changed what our `phylum_project` file supports as a result of our recent Github App addition. Changes have been made to API for handling the project file, we need to make similar changes in the CLI directly. The expected structure is as follows:

```
lockfiles:
    - path: /absolute/path.json
      type: npm
    - path: /foo/bar/requirements.txt
      type: pypi
    ...
```

# Acceptance Criteria
- [ ] We have support for multiple paths to lockfiles
- [ ] Lockfile structure/format matches with ticket outlined [here](https://github.com/phylum-dev/api/issues/699#issuecomment-1378170100)
